### ISSUE TITLE
1

### ISSUE THREAD

**Issue by mvsde** [mvsde/visual-review-demo-issues#3]
1

### Meta data

```yaml
URL: http://localhost:10001/
Platform: Linux x86_64
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Cookies: true
Language: de-DE
Languages:
  - de-DE
  - en-US
  - de
```

### Screen

```yaml
Width:  3840
Height: 1600
Ratio:  1
```

### Viewport

```yaml
Width:  1111
Height: 1459
```
