### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by mvsde** [mvsde/visual-review-demo-issues#7]
Zeugs

### Meta data

```yaml
URL: https://visual-review.pangolinjs.org/github.html
Platform: Linux x86_64
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Cookies: true
Language: de-DE
Languages:
  - de-DE
  - en-US
  - de
```

### Screen

```yaml
Width:  1920
Height: 1080
Ratio:  1.75
```

### Viewport

```yaml
Width:  1097
Height: 560
```
